### ISSUE TITLE
Frage zur Sortierung der Adressen

### ISSUE THREAD

**Issue by ansichtsache** [FriendsOfREDAXO/multinewsletter#54]
Kann die Versandbenachrichtigung eines Newsletters auch die Vor- und Zunamen vor der E-Mail anzeigen? Denn wenn ich die Adressen bei einem zweiten Versuch eingeben möchte, wird bei der Empfängerauswahl immer nach Vornamen sortiert.
Eine Sortierung nach E-Mail-Adresse oder die Anzeige der Namen würde mir die Arbeit erheblich erleichtern.
Danke!

**Comment by TobiasKrais** [comment]
Du meinst beim manuellen Versand? Ich kann nicht genau zuordnen wo du die Namen einblenden möchtest und verstehe nicht, was du mit zweiten Versuch meinst.

**Comment by ansichtsache** [comment]
Hallo Tobias, danke für deine prompte Rückmeldung.

Nein, automatischer Versand. Ich erhalte ja eine Bestätigung – und hier den Hinweis auf Fehler beim Versand:
Betreff: | Versand Newsletter abgeschlossen
Der automatisierte Versand des folgenden Newsletters wurde abgeschlossen:
**** 2023-09-23
Anzahl erfolgreich versendete Empfänger: 941
Fehler gab es beim Versand an folgende Nutzer:
- info@domainname.net
- mail@domainname.de
- etc.

Wenn hier Vorname, Name, E-Mail auftauchen würden, wäre das schon gut – oder aber die Möglichkeit beim (wiederholten) Versand die Empfängerliste nach E-Mail zu sortieren. Sie ist ja nach Vornamen sortiert.
Ich hoffe soweit verständlich?

**Comment by TobiasKrais** [comment]
Ja, jetzt verstehe ich. Danke. In der Datenbank den Versand werden nur die E-Mail-Adressen gespeichert. Es wäre möglich die Namen auszulesen (falls vorhanden). Bisher habe ich mich bier an den DSGVO Grundsatz der Datensparsamkeit gehalten.
Hast du Lust einen PR zu machen? Hier wäre die Zeile an der du ansetzen musst:
https://github.com/TobiasKrais/multinewsletter/blob/5b40b81662b83a1d9d875850bb9ed424e7f2e617/lib/MultinewsletterNewsletterManager.php#L112
Du müsstest für jede Mailadresse ein Objekt erstellen (https://github.com/TobiasKrais/multinewsletter/blob/5b40b81662b83a1d9d875850bb9ed424e7f2e617/lib/MultinewsletterUser.php#L206). Danach kannst du den Namen jedes Nutzers direkt über das Objektattribut auslesen und in die Mail einfügen.

**Comment by ansichtsache** [comment]
hi tobias, danke. das würde ich gerne – das übersteigt jedoch meine fähigkeiten.

**Comment by TobiasKrais** [comment]
Verstehe. Als Tester würdest du vermutlich zur Verfügung stehen. Ich schau mal. Wird aber ein wenig dauern. Dann melde ich mich bei dir.

**Comment by TobiasKrais** [comment]
Hi Tizian,
kannst du den Commit bitte testen: https://github.com/TobiasKrais/multinewsletter/commit/49e5f4c1531e63b4624ab4c656dc8589653bc1b9. Entspricht das so deinen Wünschen?

**Comment by ansichtsache** [comment]
hi tobias,

toll, das du schon was coden konntest!

ich teste gerne – das wird eventuell ein paar tage dauern, da ich ja nur nach versand (mit fehlern) sehen kann, ob das so funktioniert.

ich gebe dir bescheid.

schöne grüße
tizian

tizian bauer
********************************
ansichtsache TM
grafik- und web-design
********************************
fon 0171. 3146511
fax 0171. 13 3146511

stader straße 10
28205 bremen

www.ansichtsache.com
********************************
